name: zed Build

on:
  push:
    branches:
      - zed
jobs:
  zed-build:
    name: zed Build
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          # toolset: 14.4
      - name: Package Directories
        run: |
            rustup update
            rustup target add wasm32-wasi
            cd C:\ ; git clone --depth=1 https://github.com/zed-industries/zed -b v0.137.6
            cd zed ; cargo build --release
            ls target\release
      - name: Package Directories
        run: |
          mkdir C:\zed_install
          cp C:\zed\target\release\*.exe C:\zed_install
          7z a zed-windows.7z C:\zed_install
      - uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: zed-windows.7z
      - name: Update zed Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zed-build
          files: |
            zed-windows.7z