name: Demo Build

on:
  push:
    branches:
      - dart
jobs:
  demo-build:
    name: Demo Build
    runs-on: windows-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Init
        run: |
          cd C:\ ; git clone --depth 1 https://github.com/xiaoyaocz/dart_simple_live
          cd dart_simple_live\simple_live_app
          flutter pub get
          flutter build windows --release
          ls
          ls build
          ls build\windows
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: demo
      #     path: demo.7z
      # - name: Update demo Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: demo-build
      #     files: |
      #       demo.7z